### ISSUE TITLE
CWD exports incorrectly

### ISSUE THREAD

**Issue by johnpauls** [NCRN/ForestVeg#138]
The `CWD.csv` file that is exported is incorrect. It should be exporting one line for each Year X Plot X Species X Decay Class combo with the total volume for that group. Instead it is exporting one line for each piece of cwd, but the volume seems to be the total volume for all pieces from that Year-Plot-Species-Decay Class.

**Comment by blcampbell** [comment]
Is this the Advanced Summary export from "Export All Data"? 

The CWD.csv exported from it contains CWD _diameter_ vs, volume. 

Should this then be the total _diameter_ across the group (year-plot-species-decayclass)?
 
So rather than embedding the volume calculation (SOP 10 p 1), it exports the aggregated diameter data that feeds that calculation?

**Comment by johnpauls** [comment]
I now think the export as it currently stands is a better way to deal with this data,
