### ISSUE TITLE
Missing sapling DBHs not being highlighted on event reports

### ISSUE THREAD

**Issue by abrolis** [NCRN/ForestVeg#158]

**Comment by blcampbell** [comment]
Sapling DBH values are calculated with a function which outputs both live and dead stems as a string "L: ## D: ##".

Since the values are embedded into the string, the easiest way to handle this is to highlight those strings which have only "L: D:" in the function output.

The highlighting will display like so:

![image](https://user-images.githubusercontent.com/36767405/86070506-e923b880-ba4a-11ea-995e-92bbd6a80de3.png)

It is unknown based on the output if a missing L: or D: value is correct or not given that the output only displays the DBH value.  So this iteration will not highlight values like "L: 5.4 D:" or "L:  D: 12.2".

**Comment by abrolis** [comment]
@blcampbell In the example that you have given the two that have been highlighted are shrubs and should not have DBH values.  Can this only occur on tree saplings? 

This may need to be another github post, but after we have selected a shrub species, is there a way to automatically have the program select it as a shrub (which makes the DBH field disappear) so that a user can't accidentally input a DBH?  If ability to enter DHBs was "auto-disabled" for shrubs, we wouldn't need to see the DBH values for shrubs in the event report.  We only really look at that to trouble shoot an accidental DBH entry.   

Similarly, once we've selected a tree species, could it auto select it as a tree so that a user knows to enter a DBH?
