### ISSUE TITLE
Export function data does not work

### ISSUE THREAD

**Issue by johnpauls** [NCRN/ForestVeg#201]
The button to export the data throws an error. If you choose:
Summarize > Advanced Summary Tools > Export All Data 
you get an error which says 
"Error #94: Invalid use of Null".

Also I tried the Annual Data Export form the same place for 2020 it threw a different error:
"Error #3079 The specified field `[Event_Date]` could refer to more than one table listed in the FROM clause of your SQL statement."

I have never tried that export before, so that could be an old error for all I know. 
 It did export Events, Tree and Plots  .csv files though. The rest did not export.

**Comment by blcampbell** [comment]
Until this issue is fully addressed use the Annual Data Export at the bottom of the Advanced Data Summary form.
Set the year and select the location you wish to save the csvs. You will need to confirm the file name however all CSVs will be saved for the export. 

The export all data function has been temporarily disabled until the cumulative export portion of the export functionality can be fully addressed.
