### ISSUE TITLE
Veg database sapling exports do not include saplings without "habit" field

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/ForestVeg#76]
JP previously identified this issue in 2017 (see email chain I forwarded on 8/21/2018), but apparently we never resolved it. 

As it currently stands, any sapling that didn't have the "habit" field completed during monitoring (which is very common among the dead saplings, for which we don't typically record data) are not being exported in the sapling tables.

**Comment by blcampbell** [comment]
By design the export query limits the export to sapling data where habit = "Tree".

This excludes the following non-tree habits: Shrub, NULL (no value entered)

When released, the update will include both Tree and NULL habits. 

_The export will need to be revised once missing value flags are defined for records missing sapling habit data._
